name: list_accessors
description: Provides getters and setters for items of lists, starting at the beginning and the end.
version: 0.1.0
repository: https://github.com/marcelgarus/list_accessors

environment:
  sdk: ">=2.12.0 <3.0.0"
